### This file is automatically generated by Qt Design Studio.
### Do not change

set(_generated_qtquick3d_modules
{% for module_name in modules %}
    {{ module_name }}
{% endfor %}
)

function(add_generated_qtquick3d_module module_name)
    set(module_dir "${CMAKE_CURRENT_SOURCE_DIR}/${module_name}")
    set(module_qml "${module_dir}/${module_name}.qml")

    if(NOT EXISTS "${module_qml}")
        message(FATAL_ERROR "Missing generated QML file: ${module_qml}")
    endif()

    set(target_name "Generated_QtQuick3D_${module_name}")

    file(GLOB_RECURSE module_files
        LIST_DIRECTORIES false
        RELATIVE "${module_dir}"
        CONFIGURE_DEPENDS
        "${module_dir}/*"
    )

    set(module_resources "")
    foreach(file_name IN LISTS module_files)
        if(file_name STREQUAL "${module_name}.qml")
            continue()
        endif()
        if(file_name STREQUAL "qmldir")
            continue()
        endif()
        if(file_name MATCHES "\\.hints$")
            continue()
        endif()
        if(file_name MATCHES "\\.autosave$")
            continue()
        endif()
        list(APPEND module_resources "${module_name}/${file_name}")
    endforeach()

    qt_add_library(${target_name} STATIC)
    if(module_resources)
        qt6_add_qml_module(${target_name}
            URI "Generated.QtQuick3D.${module_name}"
            VERSION 1.0
            RESOURCE_PREFIX "/qt/qml"
            OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/${module_name}"
            QML_FILES
                "${module_name}/${module_name}.qml"
            RESOURCES
                ${module_resources}
        )
    else()
        qt6_add_qml_module(${target_name}
            URI "Generated.QtQuick3D.${module_name}"
            VERSION 1.0
            RESOURCE_PREFIX "/qt/qml"
            OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/${module_name}"
            QML_FILES
                "${module_name}/${module_name}.qml"
        )
    endif()
endfunction()

foreach(module_name IN LISTS _generated_qtquick3d_modules)
    add_generated_qtquick3d_module(${module_name})
endforeach()
