# Compatibility shim for ROS 2 distros that do not provide rosidl_find_package_idl
# (e.g., Galactic). Resolves an IDL path from a package's share directory.

if(NOT COMMAND rosidl_find_package_idl)
  find_package(ament_cmake_core QUIET)
  if(ament_cmake_core_FOUND)
    include(ament_index_get_resource OPTIONAL)
    include(ament_index_get_prefix_path OPTIONAL)
  endif()

  function(rosidl_find_package_idl out_var package_name idl_relpath)
    if("${package_name}" STREQUAL "")
      message(FATAL_ERROR "rosidl_find_package_idl(): package_name must not be empty")
    endif()
    if("${idl_relpath}" STREQUAL "")
      message(FATAL_ERROR "rosidl_find_package_idl(): idl_relpath must not be empty")
    endif()

    set(_share_dir "")

    if(COMMAND ament_index_get_resource)
      ament_index_get_resource(_pkg_prefix "packages" ${package_name})
      if(_pkg_prefix)
        string(STRIP "${_pkg_prefix}" _pkg_prefix)
        set(_share_dir "${_pkg_prefix}/share/${package_name}")
      endif()
    endif()

    if(NOT _share_dir AND DEFINED ${package_name}_DIR)
      get_filename_component(_share_dir "${${package_name}_DIR}" DIRECTORY)
      get_filename_component(_share_tail "${_share_dir}" NAME)
      if(NOT _share_tail STREQUAL "${package_name}")
        set(_share_dir "${_share_dir}/${package_name}")
      endif()
    endif()

    if(NOT _share_dir AND COMMAND ament_index_get_prefix_path)
      ament_index_get_prefix_path(_prefixes)
      foreach(_prefix IN LISTS _prefixes)
        set(_candidate_dir "${_prefix}/share/${package_name}")
        if(IS_DIRECTORY "${_candidate_dir}")
          set(_share_dir "${_candidate_dir}")
          break()
        endif()
      endforeach()
    endif()

    if(NOT _share_dir)
      message(DEBUG "rosidl_find_package_idl: could not locate share dir for package '${package_name}'")
      set(${out_var} "" PARENT_SCOPE)
      return()
    endif()

    set(_candidate "${_share_dir}/${idl_relpath}")
    if(EXISTS "${_candidate}")
      message(DEBUG "rosidl_find_package_idl: resolved ${package_name}:${idl_relpath} -> ${_candidate}")
      set(${out_var} "${_candidate}" PARENT_SCOPE)
      return()
    endif()

    if(DEFINED ${package_name}_IDL_FILES)
      foreach(_idl ${${package_name}_IDL_FILES})
        set(_idl_path "${_share_dir}/${_idl}")
        if(EXISTS "${_idl_path}" AND ("${_idl}" STREQUAL "${idl_relpath}"))
          message(DEBUG "rosidl_find_package_idl: resolved via IDL_FILES ${package_name}:${idl_relpath} -> ${_idl_path}")
          set(${out_var} "${_idl_path}" PARENT_SCOPE)
          return()
        endif()
      endforeach()
    endif()

    message(DEBUG "rosidl_find_package_idl: IDL '${idl_relpath}' not found under ${_share_dir}")
    set(${out_var} "" PARENT_SCOPE)
  endfunction()
endif()
