# Copyright (C) 2026 The Qt Company Ltd.
# SPDX-License-Identifier: BSD-3-Clause

FROM ubuntu:24.04

ARG ROS_DISTRO=jazzy
ARG QT_VERSION=6.11.1
ARG QT_VERSION_STUB=6111
ARG QT_INSTALL_DIR=/opt/Qt

ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Etc/UTC \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8 \
    PIP_BREAK_SYSTEM_PACKAGES=1 \
    ROS_DISTRO=${ROS_DISTRO} \
    QT_VERSION=${QT_VERSION} \
    QT_VERSION_STUB=${QT_VERSION_STUB} \
    QT_INSTALL_DIR=${QT_INSTALL_DIR} \
    QT_ROOT=${QT_INSTALL_DIR}/${QT_VERSION}/gcc_64

ENV QT_COMPONENTS=" \
    qt.qt6.${QT_VERSION_STUB}.linux_gcc_64 \
    qt.qt6.${QT_VERSION_STUB}.addons.qtquick3d \
    qt.qt6.${QT_VERSION_STUB}.addons.qtquick3dphysics \
    qt.qt6.${QT_VERSION_STUB}.addons.qtmultimedia \
    qt.qt6.${QT_VERSION_STUB}.addons.qtshadertools \
    qt.qt6.${QT_VERSION_STUB}.addons.qt5compat \
    qt.qt6.${QT_VERSION_STUB}.addons.qtimageformats\
    "

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        ninja-build \
        git \
        curl \
        wget \
        ca-certificates \
        gnupg \
        lsb-release \
        software-properties-common \
        locales \
        python3 \
        python3-pip \
        python3-venv \
        libgl1-mesa-dev \
        libglib2.0-0 \
        libxcb-cursor-dev \
        libxcb-cursor0 \
        libxcb-icccm4 \
        libxcb-image0 \
        libxcb-keysyms1 \
        libxcb-randr0 \
        libxcb-render-util0 \
        libxcb-render0 \
        libxcb-shape0 \
        libxcb-shm0 \
        libxcb-sync1 \
        libxcb-xfixes0 \
        libxcb-xinerama0 \
        libxcb-xkb1 \
        libxkbcommon-x11-0 \
        libfontconfig1 \
        libfreetype6 \
        libdbus-1-3 \
        libx11-xcb1 \
        libxi6 \
        libxrender1 \
        libxrandr2 \
        libxcursor1 \
        libxcomposite1 \
        libxdamage1 \
        libxtst6 \
        libnss3 \
        libasound2t64 \
    && locale-gen en_US en_US.UTF-8 \
    && update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 \
    && rm -rf /var/lib/apt/lists/*

RUN add-apt-repository -y universe \
    && ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}') \
    && curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo ${UBUNTU_CODENAME:-${VERSION_CODENAME}})_all.deb" \
    && dpkg -i /tmp/ros2-apt-source.deb \
    && rm -f /tmp/ros2-apt-source.deb \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        ros-${ROS_DISTRO}-desktop \
        ros-dev-tools \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir \
    urdf_parser_py \
    jinja2

WORKDIR /tmp
RUN wget -q https://download.qt.io/official_releases/online_installers/qt-online-installer-linux-x64-online.run \
    && chmod +x qt-online-installer-linux-x64-online.run

RUN --mount=type=secret,id=QT_ACCOUNT_USER_NAME \
    --mount=type=secret,id=QT_ACCOUNT_PASSWORD \
    QT_QPA_PLATFORM=minimal \
    /tmp/qt-online-installer-linux-x64-online.run \
        --verbose \
        --email "$(cat /run/secrets/QT_ACCOUNT_USER_NAME)" \
        --password "$(cat /run/secrets/QT_ACCOUNT_PASSWORD)" \
        --accept-licenses \
        --accept-obligations \
        --confirm-command \
        --root "${QT_INSTALL_DIR}" \
        install ${QT_COMPONENTS} \
    && rm -f /tmp/qt-online-installer-linux-x64-online.run

ENV PATH="${QT_ROOT}/bin:${PATH}"

RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /etc/bash.bashrc \
    && echo "export PATH=\"${QT_ROOT}/bin:\$PATH\"" >> /etc/bash.bashrc

WORKDIR /workspace
CMD ["/bin/bash"]
