# Copyright (C) 2026 The Qt Company Ltd.
# SPDX-License-Identifier: BSD-3-Clause

ARG BASE_IMAGE=qtros2-bridge:base
FROM ${BASE_IMAGE}

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

WORKDIR /workspace
COPY . .

RUN source "/opt/ros/${ROS_DISTRO}/setup.bash" \
    && mkdir -p /workspace/build \
    && cd /workspace/build \
    && qt-configure-module /workspace \
    && cmake --build . --parallel \
    && cmake --install .

CMD ["/bin/bash"]
