# Copyright (C) 2022 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR GPL-3.0-only

@# CMakeLists.txt template for QtROS2 generated code
@# Generated from IDL files - DO NOT EDIT
@#
@# This CMakeLists.txt is generated by rosidl_generator_qtros2 and included
@# via add_subdirectory() from the main rosidl generation script.
@{
# Expected context variables:
# - target_name: The target name (e.g., "builtin_interfaces_qtcpp")
# - project_name: The project name
# - source_package: The source ROS package name (e.g., "tf2_msgs")
# - qml_uri: QML module URI
# - qml_output_dir: Where to output QML module
# - qml_imports: List of QML import URIs
# - generated_headers: List of generated header files (relative paths)
# - generated_sources: List of generated source files (relative paths)
# - dependency_packages: List of ROS package dependencies
# - output_path: Base output path for includes
# - generated_parent_folders: List of interface type folders (msg, srv, action)

if 'target_name' not in locals():
    raise ValueError("target_name not provided to template")
if 'qml_uri' not in locals():
    raise ValueError("qml_uri not provided to template")
if 'generated_headers' not in locals():
    generated_headers = []
if 'generated_sources' not in locals():
    generated_sources = []
if 'qml_imports' not in locals():
    qml_imports = []
if 'dependency_packages' not in locals():
    dependency_packages = []
if 'generated_parent_folders' not in locals():
    generated_parent_folders = []
if 'source_package' not in locals():
    source_package = ''
}@
# Generated CMakeLists.txt for @(target_name)
# DO NOT EDIT - Regenerated from IDL files

cmake_minimum_required(VERSION 3.16)

# Find Qt6
find_package(Qt6 REQUIRED COMPONENTS Core Qml)

@[if source_package]@
# Find source ROS package
find_package(@(source_package) REQUIRED)
@[end if]@

# Find Qt wrapper dependencies
@[if dependency_packages]@
@[  for dep_pkg in dependency_packages]@
find_package(qtros2_@(dep_pkg) QUIET)
@[  end for]@
@[end if]@

# Create Qt library
qt_add_library(@(target_name) SHARED)

# Create alias target if it doesn't exist
if(NOT TARGET ${PROJECT_NAME}::@(target_name))
    add_library(${PROJECT_NAME}::@(target_name) ALIAS @(target_name))
endif()

# Set target properties
set_target_properties(@(target_name) PROPERTIES
    OUTPUT_NAME "@(target_name)"
    AUTOMOC ON
    CXX_STANDARD 17
    CXX_STANDARD_REQUIRED ON
)

# Set Qt policy for QML module
qt_policy(SET QTP0001 NEW)

# Create QML module
qt_add_qml_module(@(target_name)
    URI @(qml_uri)
    VERSION 1.0
@[if qml_output_dir]@
    OUTPUT_DIRECTORY "@(qml_output_dir)"
@[end if]@
@[if qml_imports]@
    IMPORTS
@[  for import_uri in qml_imports]@
        @(import_uri)
@[  end for]@
@[end if]@
    SOURCES
@[for header in generated_headers]@
        @(header)
@[end for]@
@[for source in generated_sources]@
        @(source)
@[end for]@
)

# Link Qt libraries
target_link_libraries(@(target_name) PUBLIC
    Qt6::Core
    Qt6::Qml
    qtros2_core::qtros2_core
)

@[if source_package]@
# Note: Source ROS package (@(source_package)) is linked via target_link_libraries()
# in the parent CMakeLists.txt (qtros2_generate_from_package.cmake)
@[end if]@

# Link dependency packages (Qt wrappers for message dependencies)
@[if dependency_packages]@
@[  for dep_pkg in dependency_packages]@
# Link to Qt wrapper for @(dep_pkg)
# Try namespaced target first (installed), then local target
if(TARGET qtros2_@(dep_pkg)::qtros2_@(dep_pkg)_qtcpp)
    target_link_libraries(@(target_name) PUBLIC qtros2_@(dep_pkg)::qtros2_@(dep_pkg)_qtcpp)
elseif(TARGET qtros2_@(dep_pkg)_qtcpp)
    target_link_libraries(@(target_name) PUBLIC qtros2_@(dep_pkg)_qtcpp)
endif()
@[  end for]@
@[end if]@

# Include directories
@[if output_path and generated_parent_folders]@
set(_qtros2_build_includes "${CMAKE_CURRENT_SOURCE_DIR}/include")
@[  for subdir in generated_parent_folders]@
list(APPEND _qtros2_build_includes "${CMAKE_CURRENT_SOURCE_DIR}/include/@(target_name.replace('_qtcpp', ''))/@(subdir)")
@[  end for]@
target_include_directories(@(target_name) PUBLIC
    "$<BUILD_INTERFACE:${_qtros2_build_includes}>"
    "$<INSTALL_INTERFACE:include>"
)
@[end if]@

# Add metatypes JSON as INTERFACE_SOURCES so dependent modules can find it
# Qt's qt_add_qml_module uses this to automatically collect foreign types
# Use BUILD_INTERFACE for build tree and INSTALL_INTERFACE for installed tree
get_target_property(_@(target_name)_metatypes_file @(target_name) INTERFACE_QT_META_TYPES_BUILD_FILE)
get_target_property(_@(target_name)_metatypes_name @(target_name) INTERFACE_QT_META_TYPES_FILE_NAME)

if(_@(target_name)_metatypes_file)
    set(_@(target_name)_consumes_metatypes "$<BOOL:$<TARGET_PROPERTY:QT_CONSUMES_METATYPES>>")
    set(_@(target_name)_metatypes_build "$<BUILD_INTERFACE:$<${_@(target_name)_consumes_metatypes}:${_@(target_name)_metatypes_file}>>")
    set(_@(target_name)_metatypes_install "$<INSTALL_INTERFACE:$<${_@(target_name)_consumes_metatypes}:$<INSTALL_PREFIX>/lib/metatypes/${_@(target_name)_metatypes_name}>>")
    target_sources(@(target_name) INTERFACE ${_@(target_name)_metatypes_build} ${_@(target_name)_metatypes_install})
endif()

# Add Qt version compatibility properties (for mixed Qt version builds)
set_target_properties(@(target_name) PROPERTIES
    INTERFACE_QT_MAJOR_VERSION 6
    COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
)
